#include "peripherals.h"

void LED_Init(void)
{
	Enable_RCC_AHB1(RCC_REG_AHB1_GPIOD);

	Gpio_Init(GPIOD, PIN_LED3, GPIO_REG_MODE_OUTPUT, GPIO_REG_OTYPE_PP
		, GPIO_REG_SPEED_FAST, GPIO_REG_PUPD_PULLUP);
	Gpio_Init(GPIOD, PIN_LED4, GPIO_REG_MODE_OUTPUT, GPIO_REG_OTYPE_PP
		, GPIO_REG_SPEED_FAST, GPIO_REG_PUPD_PULLUP);
	Gpio_Init(GPIOD, PIN_LED5, GPIO_REG_MODE_OUTPUT, GPIO_REG_OTYPE_PP
		, GPIO_REG_SPEED_FAST, GPIO_REG_PUPD_PULLUP);
	Gpio_Init(GPIOD, PIN_LED6, GPIO_REG_MODE_OUTPUT, GPIO_REG_OTYPE_PP
		, GPIO_REG_SPEED_FAST, GPIO_REG_PUPD_PULLUP);
}

void UART_Init(void)
{
	Enable_RCC_AHB1(RCC_REG_AHB1_GPIOC);

	Gpio_Init(GPIOC, PIN_UART3_TX, GPIO_REG_MODE_FUNCTION, GPIO_REG_OTYPE_PP
		, GPIO_REG_SPEED_FAST, GPIO_REG_PUPD_NONE);
	Gpio_Init(GPIOC, PIN_UART3_RX, GPIO_REG_MODE_FUNCTION, GPIO_REG_OTYPE_PP
		, GPIO_REG_SPEED_FAST, GPIO_REG_PUPD_NONE);

	Enable_RCC_APB1(RCC_REG_APB1_USART3);
}